###### ARTIFICIAL INTELLIGENCE ALGORITHMS
### Practical Assignment
# **#1**
---

In [168]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, r2_score

In [169]:
# Read dataset
patients_data = pd.read_csv("./pd_speech.csv")
patients_data.head(5)

Unnamed: 0 Unnamed: 1 Baseline Features Unnamed: 3 Unnamed: 4 Unnamed: 5   
0         id     gender               PPE        DFA       RPDE  numPulses  \
1          0          1           0.85247    0.71826    0.57227        240   
2          0          1           0.76686    0.69481    0.53966        234   
3          0          1           0.85083    0.67604    0.58982        232   
4          1          0           0.41121    0.79672    0.59257        178   

         Unnamed: 6        Unnamed: 7          Unnamed: 8    Unnamed: 9  ...   
0  numPeriodsPulses  meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
1               239        0.00806353            8.68E-05       0.00218  ...   
2               233       0.008258256            7.31E-05       0.00195  ...   
3               231        0.00833959            6.04E-05       0.00176  ...   
4               177       0.010857733         0.000182739       0.00419  ...   

                Unnamed: 745               Unnamed: 746   
0  tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
1                      1.562                     2.6445   
2                     1.5589                     3.6107   
3                     1.5643                     2.3308   
4                     3.7805                     3.5664   

                Unnamed: 747               Unnamed: 748   
0  tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
1                     3.8686                     4.2105   
2                    23.5155                    14.1962   
3                     9.4959                    10.7458   
4                     5.2558                    14.0403   

                Unnamed: 749               Unnamed: 750   
0  tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
1                     5.1221                     4.4625   
2                    11.0261                     9.5082   
3                    11.0177                     4.8066   
4                     4.2235                     4.6857   

                Unnamed: 751               Unnamed: 752   
0  tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
1                     2.6202                     3.0004   
2                     6.5245                     6.3431   
3                     2.9199                     3.1495   
4                      4.846                      6.265   

                Unnamed: 753 Unnamed: 754  
0  tqwt_kurtosisValue_dec_36        class  
1                    18.9405            1  
2                     45.178            1  
3                     4.7666            1  
4                     4.0603            1  

[5 rows x 755 columns]

Looking at the data, it seems like the 2nd row (1st body row) is the one that actually represents the column names. We can change to use this as column names.

In [170]:
patients_data.columns = patients_data.iloc[0,]
patients_data.drop(index=0, inplace=True)
patients_data.head(5)

0 id gender      PPE      DFA     RPDE numPulses numPeriodsPulses   
1  0      1  0.85247  0.71826  0.57227       240              239  \
2  0      1  0.76686  0.69481  0.53966       234              233   
3  0      1  0.85083  0.67604  0.58982       232              231   
4  1      0  0.41121  0.79672  0.59257       178              177   
5  1      0   0.3279  0.79782  0.53028       236              235   

0 meanPeriodPulses stdDevPeriodPulses locPctJitter  ...   
1       0.00806353           8.68E-05      0.00218  ...  \
2      0.008258256           7.31E-05      0.00195  ...   
3       0.00833959           6.04E-05      0.00176  ...   
4      0.010857733        0.000182739      0.00419  ...   
5      0.008161574        0.002668863      0.00535  ...   

0 tqwt_kurtosisValue_dec_28 tqwt_kurtosisValue_dec_29   
1                     1.562                    2.6445  \
2                    1.5589                    3.6107   
3                    1.5643                    2.3308   
4                    3.7805                    3.5664   
5                    6.1727                    5.8416   

0 tqwt_kurtosisValue_dec_30 tqwt_kurtosisValue_dec_31   
1                    3.8686                    4.2105  \
2                   23.5155                   14.1962   
3                    9.4959                   10.7458   
4                    5.2558                   14.0403   
5                    6.0805                    5.7621   

0 tqwt_kurtosisValue_dec_32 tqwt_kurtosisValue_dec_33   
1                    5.1221                    4.4625  \
2                   11.0261                    9.5082   
3                   11.0177                    4.8066   
4                    4.2235                    4.6857   
5                    7.7817                   11.6891   

0 tqwt_kurtosisValue_dec_34 tqwt_kurtosisValue_dec_35   
1                    2.6202                    3.0004  \
2                    6.5245                    6.3431   
3                    2.9199                    3.1495   
4                     4.846                     6.265   
5                    8.2103                    5.0559   

0 tqwt_kurtosisValue_dec_36 class  
1                   18.9405     1  
2                    45.178     1  
3                    4.7666     1  
4                    4.0603     1  
5                    6.1164     1  

[5 rows x 755 columns]

#### Data Analysis

In [171]:
print(patients_data.info())
print(patients_data.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 1 to 756
Columns: 755 entries, id to class
dtypes: object(755)
memory usage: 4.4+ MB
None
(756, 755)


The dataset consist of 756 samples with 755 features

In [172]:
patients_data.isnull().sum()

0
id                           0
gender                       0
PPE                          0
DFA                          0
RPDE                         0
                            ..
tqwt_kurtosisValue_dec_33    0
tqwt_kurtosisValue_dec_34    0
tqwt_kurtosisValue_dec_35    0
tqwt_kurtosisValue_dec_36    0
class                        0
Length: 755, dtype: int64

No null values are found in any of the columns

In [173]:
print(patients_data.duplicated().sum())

1


1 duplicated sample found.

In [174]:
patients_data.describe()

0        id gender      PPE      DFA     RPDE numPulses numPeriodsPulses   
count   756    756      756      756      756       756              756  \
unique  252      2      740      745      748       315              319   
top       0      1  0.82273  0.72248  0.62128       237              236   
freq      3    390        3        2        2         9                8   

0      meanPeriodPulses stdDevPeriodPulses locPctJitter  ...   
count               756                756          756  ...  \
unique              755                646          358  ...   
top         0.006004477           7.17E-05      0.00076  ...   
freq                  2                  3            9  ...   

0      tqwt_kurtosisValue_dec_28 tqwt_kurtosisValue_dec_29   
count                        756                       756  \
unique                       749                       755   
top                       1.7726                    4.0251   
freq                           2                         2   

0      tqwt_kurtosisValue_dec_30 tqwt_kurtosisValue_dec_31   
count                        756                       756  \
unique                       752                       753   
top                       2.8454                    4.2105   
freq                           2                         2   

0      tqwt_kurtosisValue_dec_32 tqwt_kurtosisValue_dec_33   
count                        756                       756  \
unique                       749                       752   
top                       2.6829                    3.1144   
freq                           2                         2   

0      tqwt_kurtosisValue_dec_34 tqwt_kurtosisValue_dec_35   
count                        756                       756  \
unique                       753                       753   
top                       12.595                    4.2391   
freq                           2                         2   

0      tqwt_kurtosisValue_dec_36 class  
count                        756   756  
unique                       754     2  
top                       3.2941     1  
freq                           2   564  

[4 rows x 755 columns]

#### Data Preprocessing

In [175]:
# Remove duplicates
patients_data.drop_duplicates(inplace=True)

#### Data Standardization

In [176]:
# Feature scaling

# scale all numeric columns in the frame.
# "id" gender" and "class" are categorical data and should be excluded from scaling.
non_numeric_columns = ["gender", "class", "id"]
numeric_columns = [
    col for col in patients_data.columns if col not in non_numeric_columns
]

scaler = StandardScaler()
patients_data[numeric_columns] = scaler.fit_transform(patients_data[numeric_columns])
patients_data.head(5)

0 id gender       PPE       DFA      RPDE  numPulses  numPeriodsPulses   
1  0      1  0.627605  0.254241  0.607415  -0.846372         -0.841852  \
2  0      1  0.121892 -0.082731  0.369956  -0.906844         -0.902212   
3  0      1  0.617917 -0.352452  0.735211  -0.927001         -0.922333   
4  1      0 -1.978992  1.381694  0.755236  -1.471252         -1.465579   
5  1      0 -2.471119  1.397501  0.301653  -0.886687         -0.882092   

0  meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...   
1          0.932476           -0.407447     -0.055085  ...  \
2          1.039095           -0.426276     -0.142605  ...   
3          1.083628           -0.443731     -0.214904  ...   
4          2.462389           -0.275590      0.709759  ...   
5          0.986158            3.141307      1.151162  ...   

0  tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29   
1                  -0.585258                  -0.619902  \
2                  -0.585331                  -0.590282   
3                  -0.585203                  -0.629519   
4                  -0.532702                  -0.591640   
5                  -0.476032                  -0.521890   

0  tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31   
1                  -0.577334                  -0.482710  \
2                   0.192194                   0.015511   
3                  -0.356924                  -0.156641   
4                  -0.523000                   0.007733   
5                  -0.490698                  -0.405295   

0  tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33   
1                  -0.399709                  -0.485012  \
2                  -0.067675                  -0.176190   
3                  -0.068147                  -0.463951   
4                  -0.450245                  -0.471351   
5                  -0.250136                  -0.042709   

0  tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35   
1                  -0.775883                  -0.815509  \
2                  -0.527468                  -0.583818   
3                  -0.756815                  -0.805174   
4                  -0.634264                  -0.589232   
5                  -0.420207                  -0.673037   

0  tqwt_kurtosisValue_dec_36  class  
1                  -0.367276      1  
2                   0.399406      1  
3                  -0.781450      1  
4                  -0.802089      1  
5                  -0.742008      1  

[5 rows x 755 columns]

#### Train Model

In [177]:
# Prepare data

# Assuming column "class" indicates the presence or absence of the disease.
X = patients_data.drop(columns=["class"])
y = patients_data["class"]

# Split data to train and test chunks.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=4408
)
# test_size=0.2 indicates train[80%]/test[20%] split.

display(X_train.head(5))
display(y_train.head(5))

0     id gender       PPE       DFA      RPDE  numPulses  numPeriodsPulses   
338  112      0  0.003749 -0.333340  1.115175  -0.916923         -0.932393  \
168   55      1  0.526533  0.154083  0.632829   0.060713          0.063559   
607  202      0  0.541301  0.425385  1.587690  -2.438809         -2.501770   
647  215      1 -2.563861  1.008511  2.078847  -1.350307         -1.375038   
565  188      0  0.649461  0.903611 -1.001278   0.715829          0.717466   

0    meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...   
338          1.033782            3.343110      1.314785  ...  \
168         -0.278146           -0.269459     -0.584008  ...   
607          0.223302            1.997436      3.373397  ...   
647          1.895675            0.095297      2.045383  ...   
565         -0.807347           -0.480840     -0.606839  ...   

0    tqwt_kurtosisValue_dec_27  tqwt_kurtosisValue_dec_28   
338                  -0.420344                  -0.499421  \
168                  -0.414199                  -0.204251   
607                  -0.318815                  -0.484456   
647                  -0.388888                  -0.533460   
565                   0.447075                  -0.274071   

0    tqwt_kurtosisValue_dec_29  tqwt_kurtosisValue_dec_30   
338                  -0.556145                  -0.511124  \
168                   0.232109                   0.360525   
607                  -0.520666                  -0.564694   
647                  -0.578525                  -0.622345   
565                  -0.211447                   0.431341   

0    tqwt_kurtosisValue_dec_31  tqwt_kurtosisValue_dec_32   
338                  -0.496860                  -0.350494  \
168                   0.136234                  -0.250232   
607                  -0.492095                  -0.510050   
647                  -0.567948                  -0.519998   
565                   1.231944                   0.939220   

0    tqwt_kurtosisValue_dec_33  tqwt_kurtosisValue_dec_34   
338                  -0.410770                  -0.625000  \
168                  -0.085050                   1.078577   
607                  -0.587787                  -0.697668   
647                  -0.493378                  -0.731733   
565                   0.904326                   0.909528   

0    tqwt_kurtosisValue_dec_35  tqwt_kurtosisValue_dec_36  
338                  -0.630507                   0.315166  
168                   1.555924                   1.790937  
607                  -0.672088                  -0.594267  
647                  -0.813894                  -0.826132  
565                   1.450541                   1.679745  

[5 rows x 754 columns]

338    1
168    1
607    1
647    1
565    1
Name: class, dtype: object

In [178]:
# Train model with train dataset

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

Now that model is trained and ready, we can evaluate it's performance

#### Evaluation

In [179]:
predictions = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, predictions)}")
print(f"R2 score: {r2_score(y_test, predictions, )}")
print(f"Precision: {precision_score(y_test, predictions, pos_label='1')}")
print(f"Recall: {recall_score(y_test, predictions, pos_label='1')}")

Accuracy: 0.8543046357615894
R2 score: 0.21242294926505434
Precision: 0.9181818181818182
Recall: 0.8859649122807017


The model exhibits good perfomance in all the metrics. With higher accuracy, r2 score, precision and moderately high recall.

#### Prediction System

In [212]:
def predict_parkinson(patient_data):
    prediction = model.predict(patient_data)
    if prediction == "1":
        print("Patient is likely to be suffering from Parkinson")
    else:
        print("Patient is unlikely to be suffering from Parkinson")


# Prediction for 5th person in dataframe.
patient_data = patients_data[4:5]
original_label = patient_data["class"]
patient_data = patient_data.drop(columns=["class"])


print(f"Original label: {original_label}")
predict_parkinson(patient_data)

Original label: 5    1
Name: class, dtype: object
Patient is likely to be suffering from Parkinson


As we can see, the original label for sample at 5th position was 1 indicating that person is suffering from Parkinson. Our model correctly predicted the person to likely have the disease.